<?php
# doit être enregistré sous le nom config.php
// paramètres de connexions
const DB_DRIVER = "mysql";
const DB_HOST = "localhost";
const DB_LOGIN = "root";
const DB_PWD = "";
const DB_NAME = "ti2web2026";
const DB_PORT = 3307; // pour MariaDB, ou le port par défaut de MySQL : 3306
const DB_CHARSET = "utf8mb4";

// pour raccourcir la connexion
const MARIA_DSN = DB_DRIVER.":host=".DB_HOST. ";dbname=".DB_NAME.";port=".DB_PORT.";charset=".DB_CHARSET.";";

// URL absolue du projet
const URL_BASE = __DIR__;

# pour la pagination (BONUS)
const PAGINATION_NB = 3; // nombre d'éléments par page
const PAGINATION_GET = "pg"; // nom de la variable GET pour la pagination


